### ISSUE TITLE
Can't Use Loader.txt so we can't use the project.

### ISSUE THREAD

**Issue by gramma69** [TheNewAttacker64/Theattacker-Crypter#12]
The Loader.txt file is over 512kb ( maximum pastebin volume ) .

My Loader.txt is 17000 kb . Is anything wrong with generating the Loader.txt in your project?

**Comment by gramma69** [comment]
By this thing, it means that no-one is able to use the crypter.

**Comment by TheNewAttacker64** [comment]
that s not an issue you can host on your  own http server
