### ISSUE TITLE
When I press the "Encrypt" button, it is not encrypted.

### ISSUE THREAD

**Issue by Hyyperx0** [TheNewAttacker64/Theattacker-Crypter#3]
It says "Copy the content of loader.txt and paste it in pastebin then copy the raw URL and paste it into Builder Area". I am doing what is said.

I select everything written in the loader.txt file with CTRL+A, copy and paste it into pastebin. Then I press the "raw" tab, copy the URL and paste it into the "Builder Area". So what should I do next? I get the same warning when I say "Encrypt".

**Comment by TheNewAttacker64** [comment]
can you please show me  a screenshot or the problem you getting ?
