### ISSUE TITLE
Please add custom stub

### ISSUE THREAD

**Issue by Xprogrammer777** [TheNewAttacker64/Theattacker-Crypter#5]
It could be epic if we can have a custom stub option.
IDK if this program has a backdoor I don't fully trust it, but that's great work. 
What's the builder area btw... Because for the moment the injecter can only do every option mentioned but where is the payload BEFORE the injection?

**Comment by TheNewAttacker64** [comment]
if you belive there is backdoor instead of saying it you have to proof it  it s still foolish to say that there  is backdoor while you have the source code

**Comment by Xprogrammer777** [comment]
> if you belive there is backdoor instead of saying it you have to proof it it s still foolish to say that there is backdoor while you have the source code

You can put a release with a backdoor and put the source code without it. 
Also I'm mainly a python coder and reading someone else code without a big amount of comment in a language that I don't really know is kinda hard for me.

**Comment by TheNewAttacker64** [comment]
you could use dnspy to read the code  i don t think it s issue to  accuse project of backdoor without any proof so i will close this issue
