### ISSUE TITLE
Pastebin does not work over 512kb

### ISSUE THREAD

**Issue by NightFuryPrime** [TheNewAttacker64/Theattacker-Crypter#7]
Hello
i tried pastebin and it does not work, i exceeded the quota, i tried my own server where i paste it in .txt file does not work.

any ideas how to proceed?

**Comment by TheNewAttacker64** [comment]
that s not an issue you did something wrong

**Comment by NightFuryPrime** [comment]
i did not, is it possible to load it from local pc instead of pastebin?

**Comment by TheNewAttacker64** [comment]
Loading locally i still didn t add that i might add it soon

**Comment by NightFuryPrime** [comment]
can you upload video tutorial let say on vimeo instead of youtube where it gets deleted?

**Comment by TheNewAttacker64** [comment]
sorry won t record videos anymore if anybody else of the users want to record one i will link to it

**Comment by NightFuryPrime** [comment]
can you at least tell me how to use pastebin my loader.txt has over 1000kb and when i paste it into pastebin i get error that all characters has been used up limited to 512kb?

**Comment by TheNewAttacker64** [comment]
again that s not an issue pls stop chatting in the issue section   if you just upload the file into any other palce and get raw url it will work

**Comment by NightFuryPrime** [comment]
i uploaded it here and it does not work https://kazybot.8u.cz/huh.txt

**Comment by TheNewAttacker64** [comment]
i m sorry i can t help you  i won t reply anymore  if another reply on the same issue
