### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Miche1355** [TheNewAttacker64/Theattacker-Crypter#8]
I have a problem, how can I contact you? THANK YOU

**Comment by TheNewAttacker64** [comment]
Report your problem  here please

**Comment by Miche1355** [comment]
I tried with the crypter, but it doesn't work with my metasploit payload.
It worked well with PayGen.

**Comment by TheNewAttacker64** [comment]
i m not working on PayGen anymore

**Comment by Miche1355** [comment]
Well that's a shame :/
I am looking for a paygen download link?

**Comment by TheNewAttacker64** [comment]
i deleted it for some reasons

**Comment by Miche1355** [comment]
To create the payload as paygen it was first PSH then converted to py?
